### PR TITLE
Fix closing time

### PR DESCRIPTION
**Pull request by kholbekj**
Judging by the timeline, this looks like a typo?

### CODE REVIEW

**Comment by emrox** [comment]
Good spot! Thx for noticing, but the closing time is correct, just the time for the family photo is wrong since this will happen on Saturday.

**Comment by kholbekj** [comment]
Hah, then my train tickets are a bit late! 😂 

Fixed

**Review by emrox — APPROVED** [review]

**Comment by emrox** [comment]
weather should be nice and the location is not too far away from the Alster. So you can enjoy some time relaxing there. (Or just help us cleaning up 😅)

**Comment by kholbekj** [comment]
Hah, yeah, for sure will find things to do <3 Looking forward!

**Pull request merged**
